CREATE TABLE account (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_password VARCHAR NOT NULL,
  subscription_expiry TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR,
  billing VARCHAR,
  batch_start_date TIMESTAMP WITH TIME ZONE,
  batch_end_date TIMESTAMP WITH TIME ZONE,
  email_id BIGINT NOT NULL REFERENCES email(id) ON DELETE CASCADE ON UPDATE CASCADE,
  product_variant_id BIGINT NOT NULL REFERENCES product_variant(id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
