CREATE TABLE email_subject (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  context VARCHAR NOT NULL,
  subject VARCHAR NOT NULL,
  extract_method VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
