CREATE TABLE transaction_item (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  transaction_id VARCHAR NOT NULL REFERENCES transaction(id) ON DELETE CASCADE ON UPDATE CASCADE,
  account_user_id BIGINT REFERENCES account_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
