CREATE TABLE account_modifier (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  modifier_id VARCHAR NOT NULL,
  account_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE ON UPDATE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  metadata TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
