CREATE TABLE email (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
) WITH (fillfactor=90);

CREATE TRIGGER email_set_updated_at
BEFORE UPDATE ON email
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
