CREATE TABLE tenant (
    id VARCHAR PRIMARY KEY NOT NULL,
    secret VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
