CREATE TABLE task_queue (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    execute_at TIMESTAMP WITH TIME ZONE NOT NULL,
    subject_id VARCHAR NOT NULL,
    context VARCHAR NOT NULL,
    payload VARCHAR NOT NULL,
    status VARCHAR,
    error_message VARCHAR,
    tenant_id VARCHAR NOT NULL REFERENCES tenant(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
