CREATE TABLE tele_notifier (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    chat_thread_id BIGINT,
    context VARCHAR NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id VARCHAR NOT NULL REFERENCES tenant(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
