CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE gcp_projects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(100) NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    client_secret VARCHAR(255) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    active_count INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TRIGGER gcp_projects_set_updated_at
BEFORE UPDATE ON gcp_projects
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE email_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    provider VARCHAR(20) NOT NULL, -- 'gmail', 'outlook', 'imap'
    status VARCHAR(30) DEFAULT 'ACTIVE' NOT NULL, -- 'ACTIVE', 'ERROR', 'REAUTH_REQUIRED', 'CONNECTION_SUSPENDED'
    gcp_project_id INT REFERENCES gcp_projects(id) ON DELETE SET NULL,
    credentials TEXT NOT NULL, -- JSON string storing plaintext connection credentials
    last_sync_at TIMESTAMP WITH TIME ZONE,
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE(tenant_id, email)
);

CREATE TRIGGER email_accounts_set_updated_at
BEFORE UPDATE ON email_accounts
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX idx_email_accounts_tenant ON email_accounts(tenant_id);
CREATE INDEX idx_email_accounts_gcp_project ON email_accounts(gcp_project_id);
